package Interfaces;

import Clases.Producto;
import Clases.SQLServer;
import javax.swing.JOptionPane;

public class jPActualizarProducto extends javax.swing.JPanel {

    SQLServer metodos;
    Producto producto;

    public jPActualizarProducto() {
        initComponents();
        metodos = new SQLServer();
        producto = new Producto();
        metodos.mostrarProductos(jtProductos);
        lblFiltroNom.setVisible(false);
        lblFiltroCat.setVisible(false);
        txtNomFiltro.setVisible(false);
        jcbFiltroCat.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelHeader = new javax.swing.JPanel();
        lblHeaderTitle = new javax.swing.JLabel();
        lblIconHeader = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNomProd = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtDescProd = new javax.swing.JTextField();
        txtCodProd = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtPesoProd = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtPrecioProd = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jcbCatProd = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        btnActualizar = new javax.swing.JButton();
        jspCantCacao = new javax.swing.JSpinner();
        jspCantStock = new javax.swing.JSpinner();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtProductos = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jcbFiltroMain = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        lblFiltroCod = new javax.swing.JLabel();
        txtCodProdBuscar = new javax.swing.JTextField();
        lblFiltroNom = new javax.swing.JLabel();
        txtNomFiltro = new javax.swing.JTextField();
        lblFiltroCat = new javax.swing.JLabel();
        jcbFiltroCat = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        btnBuscarProd = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblHeaderTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblHeaderTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblHeaderTitle.setText("Actualizar producto");

        lblIconHeader.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir")+"\\src\\main\\java\\img\\icon_actualizarHeader.png"));

        javax.swing.GroupLayout panelHeaderLayout = new javax.swing.GroupLayout(panelHeader);
        panelHeader.setLayout(panelHeaderLayout);
        panelHeaderLayout.setHorizontalGroup(
            panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHeaderLayout.createSequentialGroup()
                .addGap(210, 210, 210)
                .addComponent(lblIconHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblHeaderTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(212, Short.MAX_VALUE))
        );
        panelHeaderLayout.setVerticalGroup(
            panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblIconHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(panelHeaderLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblHeaderTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        add(panelHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 739, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del producto"));

        jLabel1.setText("Nombre del producto:");

        txtNomProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomProdActionPerformed(evt);
            }
        });
        txtNomProd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNomProdKeyReleased(evt);
            }
        });

        jLabel2.setText("Descripción del producto:");

        txtDescProd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDescProdKeyReleased(evt);
            }
        });

        txtCodProd.setEditable(false);
        txtCodProd.setEnabled(false);
        txtCodProd.setOpaque(true);

        jLabel3.setText("Código del producto:");

        jLabel4.setText("Peso neto(g):");

        txtPesoProd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesoProdKeyReleased(evt);
            }
        });

        jLabel8.setText("Categoría del producto");

        jLabel9.setText("Cantidad en stock:");

        txtPrecioProd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPrecioProdKeyReleased(evt);
            }
        });

        jLabel10.setText("Precio $:");

        jcbCatProd.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chocolate y confitería", "Bebidas de cacao", "Productos en polvo", "Aceites", "Repostería", "Artesanales", "Orgánicos", "Decoración" }));
        jcbCatProd.setEnabled(false);

        jLabel11.setText("Cantidad en cacao del producto %:");

        btnActualizar.setText("Actualizar datos del producto");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        jspCantCacao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jspCantCacaoKeyReleased(evt);
            }
        });

        jspCantStock.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jspCantStockKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNomProd, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDescProd, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCodProd, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPesoProd, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jspCantStock, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtPrecioProd, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jspCantCacao))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcbCatProd, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 3, Short.MAX_VALUE)))))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNomProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDescProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCodProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel10)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPesoProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPrecioProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbCatProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jspCantCacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jspCantStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnActualizar)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(28, 28, 28)))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 440, 990, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Tabla de productos"));

        jtProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Código del producto", "Nombre del producto", "Precio", "Cantidad en stock", "Categoría"
            }
        ));
        jtProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtProductosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtProductos);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 968, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                .addContainerGap())
        );

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, 990, 180));

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Filtros de busqueda"));

        jLabel6.setText("Seleccione mediante que filtro se va a buscar:");

        jcbFiltroMain.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Código del producto", "Nombre del producto", "Categoría del producto" }));
        jcbFiltroMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbFiltroMainActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbFiltroMain, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jcbFiltroMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 320, 160));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Búsqueda del producto"));

        lblFiltroCod.setText("Ingrese el código del producto a buscar:");

        lblFiltroNom.setText("Ingrese el nombre del producto a buscar:");

        lblFiltroCat.setText("Seleccione la categoría:");

        jcbFiltroCat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chocolate y confitería", "Bebidas de cacao", "Productos en polvo", "Aceites", "Repostería", "Artesanales", "Orgánicos", "Decoración" }));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFiltroCod, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFiltroNom)
                    .addComponent(lblFiltroCat))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcbFiltroCat, 0, 178, Short.MAX_VALUE)
                    .addComponent(txtCodProdBuscar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtNomFiltro, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFiltroCod)
                    .addComponent(txtCodProdBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFiltroNom)
                    .addComponent(txtNomFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFiltroCat)
                    .addComponent(jcbFiltroCat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 100, 440, 150));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Opciones"));

        btnBuscarProd.setText("Buscar producto");
        btnBuscarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarProdActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar datos");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarProd, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBuscarProd)
                .addGap(18, 18, 18)
                .addComponent(btnLimpiar)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 100, 190, 150));
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomProdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomProdActionPerformed

    private void jtProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtProductosMouseClicked
        int filaSeleccionada = jtProductos.getSelectedRow();

        if (filaSeleccionada >= 0) {
            String codigoProductoSeleccionado = jtProductos.getValueAt(filaSeleccionada, 0).toString();

            // Llamar al método setearProducto para obtener los datos del producto
            Producto productoSeleccionado = metodos.setearProducto(codigoProductoSeleccionado);

            // Establecer los datos del producto en los campos de texto
            txtCodProd.setText(productoSeleccionado.getCodProducto());
            txtNomProd.setText(productoSeleccionado.getNombreProducto());
            txtDescProd.setText(productoSeleccionado.getDescripcionProducto());
            txtPrecioProd.setText(String.valueOf(productoSeleccionado.getPrecioUnit()));
            txtPesoProd.setText(String.valueOf(productoSeleccionado.getPesoNeto()));
            jcbCatProd.setSelectedItem(productoSeleccionado.getCatProd());
            jspCantStock.setValue(productoSeleccionado.getCantStock());
            jspCantCacao.setValue(productoSeleccionado.getContCacao());
        }
    }//GEN-LAST:event_jtProductosMouseClicked

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // Obtener los datos de los campos de texto
        String codProducto = txtCodProd.getText();
        String nombreProducto = txtNomProd.getText();
        String descripcionProducto = txtDescProd.getText();
        double precioUnit = Double.parseDouble(txtPrecioProd.getText());
        double pesoNeto = Double.parseDouble(txtPesoProd.getText());
        String categoriaProducto = jcbCatProd.getSelectedItem().toString();
        double contCacao = Double.parseDouble(jspCantCacao.getValue().toString());
        int cantStock = Integer.parseInt(jspCantStock.getValue().toString());

        // Crear un objeto Producto con los datos
        Producto productoActualizado = new Producto(
                codProducto, nombreProducto, descripcionProducto, categoriaProducto,
                precioUnit, pesoNeto, cantStock, contCacao, true, true
        );

        // Llamar al método en SQLServer para actualizar el producto
        boolean actualizado = metodos.actualizarProducto(productoActualizado);

        if (actualizado) {
            JOptionPane.showMessageDialog(null, "Producto actualizado con éxito", "SIGCH", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, "Error al actualizar producto", "SIGCH", JOptionPane.ERROR_MESSAGE);
        }

        // Actualizar la tabla de productos
        metodos.mostrarProductos(jtProductos);
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void jcbFiltroMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbFiltroMainActionPerformed
        switch (jcbFiltroMain.getSelectedIndex()) {
            case 0:
                lblFiltroCod.setVisible(true);
                txtCodProdBuscar.setVisible(true);
                lblFiltroNom.setVisible(false);
                lblFiltroCat.setVisible(false);
                txtNomFiltro.setVisible(false);
                jcbFiltroCat.setVisible(false);
                break;
            case 1:
                lblFiltroNom.setVisible(true);
                lblFiltroCat.setVisible(false);
                txtNomFiltro.setVisible(true);
                jcbFiltroCat.setVisible(false);
                lblFiltroCod.setVisible(false);
                txtCodProdBuscar.setVisible(false);
                break;
            case 2:
                lblFiltroNom.setVisible(false);
                lblFiltroCat.setVisible(true);
                txtNomFiltro.setVisible(false);
                jcbFiltroCat.setVisible(true);
                lblFiltroCod.setVisible(false);
                txtCodProdBuscar.setVisible(false);
                break;
            default:
                throw new AssertionError();
        }
    }//GEN-LAST:event_jcbFiltroMainActionPerformed

    private void btnBuscarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarProdActionPerformed
        switch (jcbFiltroMain.getSelectedIndex()) {
            case 0:
                metodos.mostrarProductoBuscado(jtProductos, txtCodProdBuscar.getText());
                limpiarDatosProducto();
                break;
            case 1:
                metodos.mostrarProductosPorNombre(jtProductos, txtNomFiltro.getText());
                limpiarDatosProducto();
                break;
            case 2:
                metodos.mostrarProductosPorCategoria(jtProductos, jcbFiltroCat.getSelectedItem().toString());
                limpiarDatosProducto();
                break;
            default:
                throw new AssertionError();
        }
    }//GEN-LAST:event_btnBuscarProdActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiarDatosProducto();
        metodos.mostrarProductos(jtProductos);
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void txtNomProdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomProdKeyReleased
        // Obtener el texto del JTextField
        String texto = txtNomProd.getText();

        // Usar una expresión regular para validar el texto
        if (!texto.matches("^[a-zA-ZáéíóúÁÉÍÓÚüÜñÑ\\s]*$")) {
            // Si el texto no coincide con la expresión regular, mostrar un mensaje de error
            mostrarMensajeError("Debe ingresar solo letras.");
            // Limpiar el JTextField o eliminar caracteres no válidos si es necesario
            txtNomProd.setText(texto.replaceAll("[^a-zA-ZáéíóúÁÉÍÓÚüÜñÑ\\s]", ""));
        }
    }//GEN-LAST:event_txtNomProdKeyReleased

    private void txtDescProdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescProdKeyReleased
        // Obtener el texto del JTextField
        String texto = txtDescProd.getText();

        // Usar una expresión regular para validar el texto
        if (!texto.matches("^[a-zA-ZáéíóúÁÉÍÓÚüÜñÑ\\s]*$")) {
            // Si el texto no coincide con la expresión regular, mostrar un mensaje de error
            mostrarMensajeError("Debe ingresar solo letras.");
            // Limpiar el JTextField o eliminar caracteres no válidos si es necesario
            txtDescProd.setText(texto.replaceAll("[^a-zA-ZáéíóúÁÉÍÓÚüÜñÑ\\s]", ""));
        }
    }//GEN-LAST:event_txtDescProdKeyReleased

    private void txtPrecioProdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecioProdKeyReleased
        String texto = txtPrecioProd.getText();

        try {
            double precio = Double.parseDouble(texto);
            if (precio < 0) {
                mostrarMensajeError("El precio no puede ser negativo.");
                txtPrecioProd.setText(""); // Limpiar el campo si es negativo
            }
        } catch (NumberFormatException e) {
            mostrarMensajeError("Precio no válido. Debe ser un número.");
            txtPrecioProd.setText(""); // Limpiar el campo si no es un número válido
        }
    }//GEN-LAST:event_txtPrecioProdKeyReleased

    private void txtPesoProdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesoProdKeyReleased
        String texto = txtPesoProd.getText();

        try {
            double precio = Double.parseDouble(texto);
            if (precio < 0) {
                mostrarMensajeError("El peso no puede ser negativo.");
                txtPesoProd.setText(""); // Limpiar el campo si es negativo
            }
        } catch (NumberFormatException e) {
            mostrarMensajeError("Peso neto no válido. Debe ser un número.");
            txtPesoProd.setText(""); // Limpiar el campo si no es un número válido
        }
    }//GEN-LAST:event_txtPesoProdKeyReleased

    private void jspCantStockKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jspCantStockKeyReleased
        String texto = jspCantStock.getValue().toString();

        try {
            int cantidad = Integer.parseInt(texto);
            if (cantidad <= 0) {
                mostrarMensajeError("La cantidad en stock debe ser mayor que 0.");
                jspCantStock.setValue(""); // Limpiar el campo si es menor o igual a 0
            }
        } catch (NumberFormatException e) {
            mostrarMensajeError("Cantidad en stock no válida. Debe ser un número entero.");
            jspCantStock.setValue(""); // Limpiar el campo si no es un número válido
        }
    }//GEN-LAST:event_jspCantStockKeyReleased

    private void jspCantCacaoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jspCantCacaoKeyReleased
        String texto = jspCantCacao.getValue().toString();

        try {
            int cantidad = Integer.parseInt(texto);
            if (cantidad <= 0) {
                mostrarMensajeError("La cantidad en stock debe ser mayor que 0.");
                jspCantCacao.setValue(""); // Limpiar el campo si es menor o igual a 0
            }
        } catch (NumberFormatException e) {
            mostrarMensajeError("Cantidad en stock no válida. Debe ser un número entero.");
            jspCantCacao.setValue(""); // Limpiar el campo si no es un número válido
        }
    }//GEN-LAST:event_jspCantCacaoKeyReleased

    public void limpiarDatosProducto() {
        txtCodProd.setText("");
        txtCodProdBuscar.setText("");
        txtDescProd.setText("");
        txtNomProd.setText("");
        txtPesoProd.setText("");
        txtPrecioProd.setText("");
        jspCantCacao.setValue(0);
        jspCantStock.setValue(0);
        jcbCatProd.setSelectedIndex(0);
        lblFiltroNom.setVisible(false);
        lblFiltroCat.setVisible(false);
        txtNomFiltro.setVisible(false);
        jcbFiltroCat.setVisible(false);
    }

    private void mostrarMensajeError(String mensaje) {
        // Puedes mostrar el mensaje de error en un JLabel o en una ventana emergente
        JOptionPane.showMessageDialog(this, mensaje, "Error", JOptionPane.ERROR_MESSAGE);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnBuscarProd;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jcbCatProd;
    private javax.swing.JComboBox<String> jcbFiltroCat;
    private javax.swing.JComboBox<String> jcbFiltroMain;
    private javax.swing.JSpinner jspCantCacao;
    private javax.swing.JSpinner jspCantStock;
    private javax.swing.JTable jtProductos;
    private javax.swing.JLabel lblFiltroCat;
    private javax.swing.JLabel lblFiltroCod;
    private javax.swing.JLabel lblFiltroNom;
    private javax.swing.JLabel lblHeaderTitle;
    private javax.swing.JLabel lblIconHeader;
    private javax.swing.JPanel panelHeader;
    private javax.swing.JTextField txtCodProd;
    private javax.swing.JTextField txtCodProdBuscar;
    private javax.swing.JTextField txtDescProd;
    private javax.swing.JTextField txtNomFiltro;
    private javax.swing.JTextField txtNomProd;
    private javax.swing.JTextField txtPesoProd;
    private javax.swing.JTextField txtPrecioProd;
    // End of variables declaration//GEN-END:variables
}
