package Interfaces;

import Clases.ClienteMayorista;
import Clases.ClienteParticular;
import Clases.SQLServer;
import ConexionBD.ConexionSQLServer;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.sql.Timestamp;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

public class jPAgregarCliente extends javax.swing.JPanel {

    jFAgregarClienteMayorista mayorista;
    String nomlocal, telflocal, dirlocal;
    SQLServer metodosSQL;

    public jPAgregarCliente() {
        initComponents();
        nomlocal = "";
        mayorista = new jFAgregarClienteMayorista();
        metodosSQL = new SQLServer();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        PanelDatos = new javax.swing.JPanel();
        panelHeader = new javax.swing.JPanel();
        lblHeaderTitle = new javax.swing.JLabel();
        lblIconHeader = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNomCli = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtApeCli = new javax.swing.JTextField();
        txtNroID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtDirCli = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jcbTipoID = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        txtNumCli = new javax.swing.JTextField();
        txtCorrCli = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtFechaNa = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jcbPrefCli = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jcbTipoCli = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        btnAggCli = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        lblHeaderTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblHeaderTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblHeaderTitle.setText("Agregar nuevo cliente");

        lblIconHeader.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir")+"\\src\\main\\java\\img\\icon_agregarClienteHeader.png"));

        javax.swing.GroupLayout panelHeaderLayout = new javax.swing.GroupLayout(panelHeader);
        panelHeader.setLayout(panelHeaderLayout);
        panelHeaderLayout.setHorizontalGroup(
            panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHeaderLayout.createSequentialGroup()
                .addGap(169, 169, 169)
                .addComponent(lblIconHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblHeaderTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelHeaderLayout.setVerticalGroup(
            panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHeaderLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblHeaderTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(panelHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblIconHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del cliente"));

        jLabel1.setText("Nombres:");

        txtNomCli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNomCliKeyReleased(evt);
            }
        });

        jLabel2.setText("Apellidos:");

        txtApeCli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtApeCliKeyReleased(evt);
            }
        });

        txtNroID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNroIDKeyReleased(evt);
            }
        });

        jLabel3.setText("Numero de identificación:");

        jLabel4.setText("Número de contacto:");

        txtDirCli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDirCliKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDirCliKeyTyped(evt);
            }
        });

        jLabel8.setText("Tipo de identificación:");

        jcbTipoID.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Cédula", "Pasaporte", "RUC" }));

        jLabel9.setText("Dirección de domicilio:");

        txtNumCli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNumCliKeyReleased(evt);
            }
        });

        txtCorrCli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCorrCliKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCorrCliKeyTyped(evt);
            }
        });

        jLabel5.setText("Correo electrónico:");

        jLabel7.setText("Fecha de nacimiento:");

        txtFechaNa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFechaNaKeyReleased(evt);
            }
        });

        jLabel6.setText("Preferencia de producto:");

        jcbPrefCli.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Chocolate y confitería", "Bebidas de cacao", "Productos en polvo", "Aceites", "Repostería", "Artesanales", "Orgánicos", "Decoración" }));
        jcbPrefCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbPrefCliActionPerformed(evt);
            }
        });

        jLabel10.setText("Tipo cliente:");

        jcbTipoCli.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Mayorista", "Particular" }));
        jcbTipoCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbTipoCliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(jcbTipoID, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNroID, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtFechaNa)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(jcbPrefCli, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcbTipoCli, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtNomCli, javax.swing.GroupLayout.DEFAULT_SIZE, 690, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtApeCli, javax.swing.GroupLayout.DEFAULT_SIZE, 690, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtDirCli, javax.swing.GroupLayout.DEFAULT_SIZE, 690, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtNumCli, javax.swing.GroupLayout.DEFAULT_SIZE, 690, Short.MAX_VALUE)
                                .addComponent(jLabel5)
                                .addComponent(txtCorrCli))
                            .addComponent(jLabel7))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNroID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel8)
                    .addComponent(jcbTipoID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNomCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtApeCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDirCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNumCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCorrCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFechaNa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jcbPrefCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jcbTipoCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Opciones"));

        btnAggCli.setText("Agregar ");
        btnAggCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAggCliActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addComponent(btnAggCli, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAggCli)
                    .addComponent(btnCancelar))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PanelDatosLayout = new javax.swing.GroupLayout(PanelDatos);
        PanelDatos.setLayout(PanelDatosLayout);
        PanelDatosLayout.setHorizontalGroup(
            PanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(PanelDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        PanelDatosLayout.setVerticalGroup(
            PanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDatosLayout.createSequentialGroup()
                .addComponent(panelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        mainPanel.add(PanelDatos);

        add(mainPanel);
    }// </editor-fold>//GEN-END:initComponents

    private void jcbPrefCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbPrefCliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbPrefCliActionPerformed

    private void jcbTipoCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbTipoCliActionPerformed

        switch (jcbTipoCli.getSelectedIndex()) {
            case 0:
                break;
            case 1:
                mayorista.setVisible(true);
                nomlocal = mayorista.nomLocal;
                telflocal = mayorista.telfLocal;
                dirlocal = mayorista.dirLocal;
                break;
            case 2:
                break;
            default:
                throw new AssertionError();
        }
    }//GEN-LAST:event_jcbTipoCliActionPerformed

    private void btnAggCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAggCliActionPerformed
        // Obtén el texto ingresado en el textField
        String correo = txtCorrCli.getText();

        // Expresión regular para verificar un correo electrónico gradualmente
        String regex = "^[A-Za-z0-9+_.-]*@[A-Za-z0-9+_.-]*$";

        // Compila la expresión regular en un patrón
        Pattern pattern = Pattern.compile(regex);

        // Verifica si el correo coincide con el patrón
        if (!pattern.matcher(correo).matches()) {
            mostrarMensajeError("Correo electrónico no válido.");
            return;
        }
        
        // Obtén el texto ingresado en el textField
        String fechaTexto = txtFechaNa.getText();

        // Expresión regular para verificar el formato dd/mm/aaaa de forma gradual
        String regex2 = "^([0-3]?[0-9]?)?/?([0-1]?[0-9]?)?/?([0-9]{0,4})?$";

        // Compila la expresión regular en un patrón
        Pattern pattern2 = Pattern.compile(regex2);

        // Verifica si la fecha coincide con el patrón
        if (!pattern2.matcher(fechaTexto).matches()) {
            mostrarMensajeError("Formato de fecha inválido. Utilice dd/mm/aaaa.");
            return;
        }

        // Si el formato es correcto, intenta validar la fecha
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        sdf.setLenient(false); // No permitir fechas inválidas (por ejemplo, 90/18/9999)

        try {
            Date fecha = sdf.parse(fechaTexto);
            // La fecha es válida si no se ha lanzado una excepción ParseException
        } catch (ParseException e) {
            mostrarMensajeError("Fecha no válida.");
            return;
        }
        switch (jcbTipoCli.getSelectedIndex()) {
            case 1:
                try {
                String tipoID = jcbTipoID.getSelectedItem().toString();
                String nroID = txtNroID.getText();
                String nomCli = txtNomCli.getText();
                String apeCli = txtApeCli.getText();
                String dirCli = txtDirCli.getText();
                String correoCli = txtCorrCli.getText();
                String numCli = txtNumCli.getText();
                String fechaNa = txtFechaNa.getText();
                String prefProd = jcbPrefCli.getSelectedItem().toString();
                String tipoCli = jcbTipoCli.getSelectedItem().toString();
                String a = mayorista.nomLocal;
                String b = mayorista.telfLocal;
                String c = mayorista.dirLocal;
                int prefCli = jcbPrefCli.getSelectedIndex();
                boolean estadoActivo = true;

                SimpleDateFormat formatoFecha = new SimpleDateFormat("dd/MM/yyyy");
                Date fechaNacimiento = formatoFecha.parse(fechaNa);
                Timestamp fechaNaci = new Timestamp(fechaNacimiento.getTime());

                // Obtener la fecha actual del sistema
                Date fechaActual = new Date();
                SimpleDateFormat formatoFechaActual = new SimpleDateFormat("dd/MM/yyyy");
                String fechaIngresoStr = formatoFechaActual.format(fechaActual);

                // Convertir la fecha actual formateada a un objeto Timestamp
                Timestamp fechaIngreso = new Timestamp(fechaActual.getTime());

                // Ahora puedes crear un objeto ClienteParticular con los datos recopilados
                ClienteMayorista cliente = new ClienteMayorista(nroID, tipoID, nomCli, apeCli, dirCli, correoCli, numCli, prefProd, tipoCli, a, b, c, fechaNaci, estadoActivo);
                if (cliente.validadorDeCedula(nroID) == true) {
                    metodosSQL.GuardarClienteMayorista(cliente, prefCli);
                    limpiarDatosCliente();
                } else {
                    JOptionPane.showMessageDialog(null, "Número de cédula no valida");
                    limpiarDatosCliente();
                }
            } catch (ParseException ex) {
                System.out.println(ex);
            } catch (SQLException ex) {
                Logger.getLogger(jPAgregarCliente.class.getName()).log(Level.SEVERE, null, ex);
            }
            break;
            case 2:
                 try {
                String tipoID = jcbTipoID.getSelectedItem().toString();
                String nroID = txtNroID.getText();
                String nomCli = txtNomCli.getText();
                String apeCli = txtApeCli.getText();
                String dirCli = txtDirCli.getText();
                String correoCli = txtCorrCli.getText();
                String numCli = txtNumCli.getText();
                String fechaNa = txtFechaNa.getText();
                String prefProd = jcbPrefCli.getSelectedItem().toString();
                String tipoCli = jcbTipoCli.getSelectedItem().toString();
                int prefCli = jcbPrefCli.getSelectedIndex();
                boolean estadoActivo = true;
                SimpleDateFormat formatoFecha = new SimpleDateFormat("dd/MM/yyyy");
                Date fechaNacimiento = formatoFecha.parse(fechaNa);
                Timestamp fechaNaci = new Timestamp(fechaNacimiento.getTime());

                // Obtener la fecha actual del sistema
                Date fechaActual = new Date();
                SimpleDateFormat formatoFechaActual = new SimpleDateFormat("dd/MM/yyyy");
                String fechaIngresoStr = formatoFechaActual.format(fechaActual);

                // Convertir la fecha actual formateada a un objeto Timestamp
                Timestamp fechaIngreso = new Timestamp(fechaActual.getTime());

                // Ahora puedes crear un objeto ClienteParticular con los datos recopilados
                ClienteParticular cliente = new ClienteParticular(nroID, tipoID, nomCli, apeCli, dirCli, correoCli, numCli, fechaNaci, prefProd, tipoCli, estadoActivo);
                if (cliente.validadorDeCedula(nroID) == true) {
                    metodosSQL.GuardarClienteParticular(cliente, prefCli);
                    limpiarDatosCliente();
                } else {
                    JOptionPane.showMessageDialog(null, "Número de cédula no valida");
                    limpiarDatosCliente();
                }
            } catch (ParseException ex) {
                System.out.println(ex);
            } catch (SQLException ex) {
                Logger.getLogger(jPAgregarCliente.class.getName()).log(Level.SEVERE, null, ex);
            }
            break;
            default:
                limpiarDatosCliente();
        }


    }//GEN-LAST:event_btnAggCliActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        limpiarDatosCliente();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtNroIDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNroIDKeyReleased
        int comboBoxIndex = jcbTipoCli.getSelectedIndex();

        // Obtener el texto del campo de texto
        String texto = txtNroID.getText();

        // Realizar la validación según el índice del JComboBox
        if (comboBoxIndex == 0) {
            // Validar para hasta 10 dígitos numéricos
            if (!texto.matches("\\d{0,10}")) {
                mostrarMensajeError("Debe ingresar hasta 10 dígitos numéricos.");
                txtNroID.setText(""); // Limpiar el campo
            }
        } else if (comboBoxIndex == 2) {
            // Validar para hasta 13 dígitos numéricos
            if (!texto.matches("\\d{0,13}")) {
                mostrarMensajeError("Debe ingresar hasta 13 dígitos numéricos.");
                txtNroID.setText(""); // Limpiar el campo
            }
        }
        // No hacer nada si el índice es 2 o más (índice 3 en tu caso)
    }//GEN-LAST:event_txtNroIDKeyReleased

    private void txtNomCliKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomCliKeyReleased
        // Obtener el texto del JTextField
        String texto = txtNomCli.getText();

        // Usar una expresión regular para validar el texto
        if (!texto.matches("^[a-zA-ZáéíóúÁÉÍÓÚüÜñÑ\\s]*$")) {
            // Si el texto no coincide con la expresión regular, mostrar un mensaje de error
            mostrarMensajeError("Debe ingresar solo letras.");
            // Limpiar el JTextField o eliminar caracteres no válidos si es necesario
            txtNomCli.setText(texto.replaceAll("[^a-zA-ZáéíóúÁÉÍÓÚüÜñÑ\\s]", ""));
        }
    }//GEN-LAST:event_txtNomCliKeyReleased

    private void txtApeCliKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApeCliKeyReleased
        // Obtener el texto del JTextField
        String texto = txtApeCli.getText();

        // Usar una expresión regular para validar el texto
        if (!texto.matches("^[a-zA-ZáéíóúÁÉÍÓÚüÜñÑ\\s]*$")) {
            // Si el texto no coincide con la expresión regular, mostrar un mensaje de error
            mostrarMensajeError("Debe ingresar solo letras.");
            // Limpiar el JTextField o eliminar caracteres no válidos si es necesario
            txtApeCli.setText(texto.replaceAll("[^a-zA-ZáéíóúÁÉÍÓÚüÜñÑ\\s]", ""));
        }
    }//GEN-LAST:event_txtApeCliKeyReleased

    private void txtDirCliKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDirCliKeyReleased
        // Obtener el texto del JTextField
        String texto = txtDirCli.getText();

        // Limitar la longitud máxima a 200 caracteres
        if (texto.length() > 200) {
            // Si se supera la longitud máxima, mostrar un mensaje de error
            mostrarMensajeError("La dirección no puede superar los 200 caracteres.");
            // Recortar el texto a 200 caracteres
            txtDirCli.setText(texto.substring(0, 200));
        }

        // Usar una expresión regular para validar el texto permitiendo caracteres especiales
        if (!texto.matches("^[a-zA-Z0-9áéíóúÁÉÍÓÚüÜñÑ: \\-#./\\s]*$")) {
            // Si el texto no coincide con la expresión regular, mostrar un mensaje de error
            mostrarMensajeError("La dirección contiene caracteres no válidos.");
            // Limpiar el JTextField o eliminar caracteres no válidos si es necesario
            txtDirCli.setText(texto.replaceAll("[^a-zA-ZáéíóúÁÉÍÓÚüÜñÑ: -#./\\s]", ""));
        }
    }//GEN-LAST:event_txtDirCliKeyReleased

    private void txtNumCliKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumCliKeyReleased
        // Obtener el texto del JTextField
        String texto = txtNumCli.getText();

        // Validar que solo se ingresen dígitos numéricos y que no exceda los 10 dígitos
        if (!texto.matches("\\d{0,10}")) {
            // Si no cumple con la validación, mostrar un mensaje de error
            mostrarMensajeError("El número de contacto debe contener hasta 10 dígitos numéricos.");
            // Limpiar el JTextField o eliminar caracteres no válidos si es necesario
            txtNumCli.setText(texto.replaceAll("[^0-9]", ""));
        }
    }//GEN-LAST:event_txtNumCliKeyReleased

    private void txtCorrCliKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCorrCliKeyReleased

    }//GEN-LAST:event_txtCorrCliKeyReleased

    private void txtFechaNaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFechaNaKeyReleased

    }//GEN-LAST:event_txtFechaNaKeyReleased

    private void txtDirCliKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDirCliKeyTyped

    }//GEN-LAST:event_txtDirCliKeyTyped

    private void txtCorrCliKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCorrCliKeyTyped

    }//GEN-LAST:event_txtCorrCliKeyTyped

    private void mostrarMensajeError(String mensaje) {
        // Puedes mostrar el mensaje de error en un JLabel o en una ventana emergente
        JOptionPane.showMessageDialog(this, mensaje, "Error", JOptionPane.ERROR_MESSAGE);
    }

    //Limpiar variables
    public void limpiarDatosCliente() {
        txtNroID.setText("");
        txtNomCli.setText("");
        txtApeCli.setText("");
        txtDirCli.setText("");
        txtCorrCli.setText("");
        txtNumCli.setText("");
        txtNroID.setText("");
        txtFechaNa.setText("");
        jcbPrefCli.setSelectedIndex(0);
        jcbTipoCli.setSelectedIndex(0);
        jcbTipoID.setSelectedIndex(0);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelDatos;
    private javax.swing.JButton btnAggCli;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JComboBox<String> jcbPrefCli;
    private javax.swing.JComboBox<String> jcbTipoCli;
    private javax.swing.JComboBox<String> jcbTipoID;
    private javax.swing.JLabel lblHeaderTitle;
    private javax.swing.JLabel lblIconHeader;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel panelHeader;
    private javax.swing.JTextField txtApeCli;
    private javax.swing.JTextField txtCorrCli;
    private javax.swing.JTextField txtDirCli;
    private javax.swing.JTextField txtFechaNa;
    private javax.swing.JTextField txtNomCli;
    private javax.swing.JTextField txtNroID;
    private javax.swing.JTextField txtNumCli;
    // End of variables declaration//GEN-END:variables
}
